export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

// Items
export const LOAD_ITEMS = 'LOAD_ITEMS'
export const SAVE_ITEM = 'SAVE_ITEM'
export const DELETE_ITEM = 'REMOVE_ITEM'
